module.exports = {
    extends: [
      "plugin:prettier/recommended"
    ],
    plugins: ["prettier"],
    rules: {
      "prettier/prettier": "error",
      "no-debugger": "error",
      "no-dupe-args": "error",
      "no-dupe-else-if": "error",
      "no-dupe-keys": "error",
      "no-extra-semi": "error",
      "no-func-assign": "error",
      "no-irregular-whitespace": "error",
      "no-unreachable": "warn",
      "no-unexpected-multiline": "error",
      "no-unsafe-finally": "error",
      "no-unsafe-negation": "error",
      "no-unsafe-optional-chaining": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      "array-callback-return": "error",
      "curly": ["error", "all"],
      "default-param-last": "error",
      "dot-location": ["error", "property"],
      "dot-notation": "error",
      "no-caller": "error",
      "no-empty-pattern": "error",
      "no-eval": "error",
      "no-extend-native": "error",
      "no-extra-bind": "error",
      "no-floating-decimal": "error",
      "no-global-assign": "error",
      "no-implied-eval": "error",
      "no-lone-blocks": "error",
      "no-multi-spaces": "error",
      "no-new-wrappers": "error",
      "no-octal": "error",
      "no-redeclare": "error",
      "no-return-assign": "error",
      "no-return-await": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-throw-literal": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unused-expressions": "warn",
      "no-useless-catch": "warn",
      "no-useless-call": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-return": "error",
      "no-void": "error",
      "no-with": "error",
      "require-await": "error",
      "wrap-iife": ["error", "inside"],
      "yoda": "warn",
      "no-shadow": "error",
      "no-shadow-restricted-names": "error",
      "no-use-before-define": ["error", { functions: false, classes: false }],
      "array-bracket-newline": ["error", { multiline: true }],
      "brace-style": ["error", "1tbs"],
      "comma-dangle": ["error", "always-multiline"],
      "comma-spacing": ["error", { before: false, after: true }],
      "computed-property-spacing": ["error", "never"],
      "eol-last": "error",
      "func-call-spacing": "error",
      "func-style": ["error", "declaration", { allowArrowFunctions: true }],
      "key-spacing": "error",
      "keyword-spacing": "error",
      "max-len": ["error", { code: 80}],
      "multiline-ternary": ["error", "always-multiline"],
      "new-cap": "error",
      "newline-per-chained-call": "warn",
      "no-array-constructor": "warn",
      "no-bitwise": "warn",
      "no-continue": "warn",
      "no-mixed-operators": "warn",
      "no-multi-assign": "error",
      "no-nested-ternary": "warn",
      "no-new-object": "error",
      "no-plusplus": "error",
      "no-underscore-dangle": "error",
      "no-unneeded-ternary": "warn",
      "one-var": ["error", "never"],
      "prefer-object-spread": "error",
      "arrow-parens": "error",
      "no-dupe-class-members": "error",
      "no-duplicate-imports": "error",
      "no-useless-computed-key": "error",
      "no-useless-rename": "error",
      "object-shorthand": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-template": "warn",
      "require-yield": "error"
    }
}